<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\AgenteIALocal.Core\AgenteIALocal.snk</AssemblyOriginatorKeyFile>
    <PackageIcon>favicon-128.png</PackageIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="LoggingV2\**" />
    <Compile Remove="Logging\**" />
    <EmbeddedResource Remove="LoggingV2\**" />
    <EmbeddedResource Remove="Logging\**" />
    <None Remove="LoggingV2\**" />
    <None Remove="Logging\**" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\AgenteIALocalVSIX\favicon-128.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgenteIALocal.Core\AgenteIALocal.Core.csproj" />
    <ProjectReference Include="..\AgenteIALocal.Logging\AgenteIALocal.Logging.csproj" />
  </ItemGroup>

  <!-- NUEVO - ID: 20260123_212100 - Newtonsoft.Json para FileAgentSettingsProvider -->
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
