<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<SignAssembly>True</SignAssembly>
		<AssemblyOriginatorKeyFile>AgenteIALocal.snk</AssemblyOriginatorKeyFile>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="Helpers\**" />
	  <EmbeddedResource Remove="Helpers\**" />
	  <None Remove="Helpers\**" />
	</ItemGroup>
	<!-- NUEVO - ID: 20260123_225900 - Referencia a Logging para usar LogSettings en GlobalSettings -->
	<ItemGroup>
	  <ProjectReference Include="..\AgenteIALocal.Logging\AgenteIALocal.Logging.csproj" />
	</ItemGroup>
</Project>
